# Generated by Django 3.0.7 on 2020-06-12 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_reference_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
